name: Build and Release FloodgateSkript

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Find built JAR
        id: find_jar
        run: |
          jar_file=$(ls build/libs/floodgate-skript-*.jar | head -n 1)
          echo "Found JAR: $jar_file"
          echo "jar_file=$jar_file" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        if: github.ref_type != 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: floodgate-skript-jar
          path: ${{ steps.find_jar.outputs.jar_file }}

      - id: create_release
        if: github.ref_type == 'tag'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: github.ref_type == 'tag'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_jar.outputs.jar_file }}
          asset_name: floodgate-skript.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}